<?xml version="1.0" encoding="utf-8"?><Database Name="Pong" Class="PongDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=Pong;Persist Security Info=True;User ID=Pong" SettingsObjectName="PongDatabase.Properties.Settings" SettingsPropertyName="PongConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Player_HighScore" Member="HighScores" ThisKey="Id" OtherKey="PlayerId" Type="HighScore" />
      <Association Name="Player_Game" Member="Games" ThisKey="Id" OtherKey="PlayerId" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.HighScore" Member="HighScores">
    <Type Name="HighScore">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PositionInRanking" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Player_HighScore" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Played" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Player_Game" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
</Database>